"""
Django settings for myadk project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Load environment variables
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-8ff9p*t((q)9vuaedhoa8duhkikulw$yj9i@rem^+^=nhl8oif"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    ".ngrok-free.dev",
]

# You must include the protocol (https://)
CSRF_TRUSTED_ORIGINS = [
    # 'https://uncoaxing-ropable-latesha.ngrok-free.dev',
    'https://*.ngrok-free.dev',  # Optional: Trust all subdomains if your ngrok URL changes
    # ... any other trusted domains you may have
]

# Application definition

INSTALLED_APPS = [
    # pip install django-jazzmin
    "jazzmin",

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party apps
    'rest_framework',
    
    # Local apps
    'myapp', 
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "myadk.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "myadk.wsgi.application"
ASGI_APPLICATION = 'myadk.asgi.application' # Using ASGI for async ADK calls

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'  # This is usually already set; it defines the URL prefix.
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Or use '/path/to/your/staticfiles/' for an absolute path.

# Optional: If you have multiple static directories, add them here
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Example: a 'static' folder in your project root
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# --- AUTHENTICATION SETTINGS ---
# Redirect users to the chat page after logging in
LOGIN_REDIRECT_URL = '/' 
# Redirect users to the chat page (which will redirect to login) after logging out
LOGOUT_REDIRECT_URL = '/'
# Specify the URL for the login page
LOGIN_URL = '/accounts/login/' 


# --- ADK CONFIGURATION ---

# The ADK Runner and Session Service will be initialized using Django's DB connection
# ADK_APP_NAME is used for session isolation
ADK_APP_NAME = "django_adk_chat"
# ADK_USER_ID is now dynamically pulled from request.user.id in views.py
