# Generated by Django 5.2.7 on 2025-10-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appsettings",
            options={"verbose_name_plural": "App Settings"},
        ),
        migrations.AddField(
            model_name="appsettings",
            name="theme_color",
            field=models.CharField(
                default="indigo",
                help_text="Tailwind base color for the theme (e.g., indigo, purple, teal).",
                max_length=20,
            ),
        ),
    ]
